version: '2'
services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
    env_file:
      - ./url_db.env
    depends_on:
      - db
    networks:
      - external
      - internal
  db:
    image: postgres:14.4-alpine
    env_file:
      - ./production.env
    networks:
      - internal

networks:
  external:
    name: web_network
  internal:
    name: services_network