version: '2'
services:
  web1:
    image: nicopaez/password-api
  web2:
    image: nicopaez/password-api
  balanceador:
    image: nginx
    volumes: 
        - './config_nginx/site.conf:/etc/nginx/conf.d/site.conf'   
    ports:
      - "3000:3000"
    depends_on:
      - web1
      - web2